//storeConstants.js


// -------- STATUS CONSTANTS ----------------------------------------------
export const SET_PAGE = 'SET_PAGE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// -------- SPOTLIGHT CONSTANTS --------------------------------------------

export const CHANGE_LAST_SPOTLIGHT_DISPLAYED ='CHANGE_LAST_SPOTLIGHT_DISPLAYED'
export const CHANGE_LAST_SPOTLIGHT_VISIT ='CHANGE_LAST_VISIT_DISPLAYED'

// export const OPEN_CLOSE_SIDE_PANEL = 'OPEN_CLOSE_SIDE_PANEL';



// export const SHOW_SPOTLIGHT = 'SHOW_SPOTLIGHT';
// export const CLOSE_SPOTLIGHT = 'CLOSE_SPOTLIGHT';

// export const ADD_SPOTLIGHT = 'ADD_SPOTLIGHT';
// export const UPDATE_SPOTLIGHT = 'UPDATE_SPOTLIGHT';
// export const DELETE_SPOTLIGHT = 'DELETE_SPOTLIGHT';
// export const DELETE_TASK = 'DELETE_TASK';



// export const FETCH_SPOTLIGHTS = 'FETCH_SPOTLIGHTS';
// export const FETCH_ACCOUNT_INFO = 'FETCH_ACCOUNT_INFO';


// export const CHANGE_DISPLAY_SPOTLIGHT ='CHANGE_DISPLAY_SPOTLIGHT'
// export const CHANGE_TASK_COMPLETED_STATUS ='CHANGE_TASK_COMPLETED_STATUS'
// export const CHANGE_SPOTLIGHT_COMPLETED_STATUS ='CHANGE_SPOTLIGHT_COMPLETED_STATUS'
// export const CHANGE_SPOTLIGHT_START_STATUS ='CHANGE_SPOTLIGHT_START_STATUS'


// export const OPEN_SPOTLIGHT_PAGE = 'OPEN_SPOTLIGHT_PAGE'
// export const CLOSE_SPOTLIGHT_PAGE = 'CLOSE_SPOTLIGHT_PAGE'
// export const CHANGE_DISPLAY = 'CHANGE_DISPLAY';

// export const ADD_TASK = 'ADD_TASK';
// export const UPDATE_TASK_ARRAY = 'UPDATE_TASK_ARRAY';

// export const CHANGE_TIMER_STATUS = 'CHANGE_TIMER_STATUS'

// export const UPDATE_NOTE = 'UPDATE_NOTE';
// export const ADD_NOTE = 'ADD_NOTE';

