
// -- Status Constants --------

export const CHANGE_LAST_SPOTLIGHT_DISPLAYED = 'CHANGE_LAST_SPOTLIGHT_DISPLAYED';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPDATE_TASK_ARRAY = 'UPDATE_TASK_ARRAY';
export const CHANGE_STATUS_INITIAL_MESSAGE = 'CHANGE_STATUS_INITIAL_MESSAGE';
export const UPDATE_STATUS_VIEW = 'UPDATE_STATUS_VIEW';

export const UPDATE_STATUS_SPOTLIGHT = 'UPDATE_STATUS_SPOTLIGHT';

// -- Spotlight Constants --------

export const CREATE_NEW_TOP_SPOTLIGHT = 'CREATE_NEW_TOP_SPOTLIGHT'
export const CREATE_NEW_CHILD_SPOTLIGHT = 'CREATE_NEW_CHILD_SPOTLIGHT'
export const GET_LAST_SPOTLIGHT_IN_ARRAY = 'GET_LAST_SPOTLIGHT_IN_ARRAY'


export const ADD_SPOTLIGHT_TO_STORE = 'ADD_SPOTLIGHT_TO_STORE'


export const UPDATE_SPOTLIGHT_IN_STORE = 'UPDATE_SPOTLIGHT_IN_STORE'
export const CHANGE_SPOTLIGHT_COMPLETED_STATUS = 'CHANGE_SPOTLIGHT_COMPLETED_STATUS'
export const CHANGE_LAST_SPOTLIGHT_VISIT ='CHANGE_LAST_SPOTLIGHT_VISIT'